# Generated by Django 4.0.4 on 2022-05-05 19:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0002_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='item',
            new_name='item_id',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'item_id')},
        ),
    ]
